id: P006737
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:20:11.783645
source_metadata:
  id: bdr:W1KG3566
  title: བྱང་གཏེར་ཕུར་པ་ལྷ་ནག་གི་ཆོས་ཚན
  author: ''
  volumes:
    ce316be539e347a5adbb4586141c6222:
      image_group_id: I1KG3630
      title: ''
      volume_number: 1
      total_pages: 456
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
